### ISSUE TITLE
Ubuntu build fails after upgrading to 0.11.1

### ISSUE THREAD

**Issue by newamber** [orlandos-nl/Citadel#114]
**Describe the bug**

Build error on ubuntu with 0.11.1.

```
 sh build.sh
--- Build Configuration ---
Release mode: false
Static build: false
Architecture: x86_64
Install path: /home/newamber/.local/bin
--------------------------
Cleaning up old artifacts...
Generating build information file...
Building the project [swift build -j 12 -c debug -Xswiftc -g --triple x86_64-unknown-linux-gnu]...
[1/1] Planning build
Building for debugging...
/home/newamber/project/mine/mtvmm/.build/checkouts/swift-nio-ssh/Sources/NIOSSH/Keys And Signatures/NIOSSHCertifiedPublicKey.swift:759:17: error: initializer 'init(tv_sec:tv_nsec:)' is not
available due to missing import of defining module 'CDispatch'
 21 | #elseif canImport(Glibc)
 22 |     import Glibc
 23 | #elseif canImport(Musl)
    | `- note: add import of module 'CDispatch'
 24 |     import Musl
 25 | #elseif canImport(Bionic)
    :
757 | extension DispatchWallTime {
758 |     init(secondsSinceEpoch: UInt64) {
759 |         let t = timespec(tv_sec: time_t(secondsSinceEpoch), tv_nsec: 0)
    |                 `- error: initializer 'init(tv_sec:tv_nsec:)' is not available due to missing import of defining module 'CDispatch'
760 |         self = DispatchWallTime(timespec: t)
761 |     }
[7/8] Compiling NIOSSH NIOSSHCertifiedPublicKey.swift
Restoring source file...
```

**Reproducer Sample**

Build error on ubuntu with 0.11.1.

**Expected behavior**

Build pass.

**Client (please complete the following information):**
 - OS: Ubuntu 22.04
 - Client: Citadel
 - Version of Citadel, if applicable: latest

**Server (please complete the following information):**
 - OS: Ubuntu 22.04
 - Server: openssh
 - Version of Citadel, if applicable:

**Additional context**

https://github.com/apple/swift-nio-ssh/pull/185 might fix this issue.

**Comment by newamber** [comment]
> Does this only happen under MUSL?

Actually, the static + musl compilation works fine; the issue occurs with regular compilation (glibc), which can be reproduced using `swift build`.

**Comment by newamber** [comment]
> Does this only happen under MUSL?

And I tried https://github.com/apple/swift-nio-ssh/pull/185, which can resolve the compilation issue, but I'm not entirely sure whether merging this PR alone might cause other side effects—for example, it might require a series of dependent patches to avoid other problems.

**Comment by florentmorin** [comment]
Hello.

PR is available. Inside the PR, I also included a sample code available as hotfix.

```swift
dependencies: [
    .package(url: "https://github.com/florentmorin/Citadel.git", branch: "fix-compilation-issues-with-linux")
],
```

**Comment by florentmorin** [comment]
@Joannis Thanks for merging. I think a new tag is required on repository for package resolution.
